import {
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  AlignmentType,
} from "docx";
import type { CandidateDossier, EvidenceClaim } from "@/lib/types";

function parasFromContent(content: string): Paragraph[] {
  const blocks = content.split(/\n+/).map((l) => l.trim()).filter(Boolean);
  if (blocks.length === 0) {
    return [
      new Paragraph({
        children: [new TextRun({ text: "—", italics: true, size: 20 })],
        spacing: { after: 200 },
      }),
    ];
  }
  return blocks.map(
    (line) =>
      new Paragraph({
        children: [new TextRun({ text: line, size: 20 })],
        spacing: { after: 160 },
      })
  );
}

export async function buildDossierDocx(input: {
  dossier: CandidateDossier;
  templateName?: string;
  mandateTitle?: string;
}): Promise<Blob> {
  const { dossier, templateName, mandateTitle } = input;
  const unsupported = dossier.claims.filter((c) => !c.supported);

  const children: Paragraph[] = [
    new Paragraph({
      text: dossier.candidateName,
      heading: HeadingLevel.TITLE,
      spacing: { after: 120 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `${dossier.targetRole} · ${dossier.client}`,
          size: 22,
          color: "555555",
        }),
      ],
      spacing: { after: 80 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: [
            templateName ? `Template: ${templateName}` : null,
            mandateTitle ? `Mandate: ${mandateTitle}` : null,
            `Status: ${dossier.status}`,
            dossier.approvedAt
              ? `Approved: ${new Date(dossier.approvedAt).toLocaleString()}`
              : "Not yet approved",
          ]
            .filter(Boolean)
            .join(" · "),
          size: 18,
          color: "777777",
        }),
      ],
      spacing: { after: 320 },
    }),
  ];

  for (const section of dossier.sections) {
    children.push(
      new Paragraph({
        text: section.title,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 280, after: 120 },
      }),
      ...parasFromContent(section.content)
    );
  }

  if (dossier.claims.length > 0) {
    children.push(
      new Paragraph({
        text: "Evidence appendix",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 360, after: 120 },
      })
    );
    for (const claim of dossier.claims) {
      children.push(...claimParagraphs(claim));
    }
  }

  if (unsupported.length > 0) {
    children.push(
      new Paragraph({
        text: "Unsupported claims (review before client release)",
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 280, after: 120 },
      }),
      ...unsupported.map(
        (c) =>
          new Paragraph({
            children: [
              new TextRun({
                text: `• ${c.claim}${c.flaggedReason ? ` — ${c.flaggedReason}` : ""}`,
                size: 18,
                color: "8B0000",
              }),
            ],
            spacing: { after: 80 },
          })
      )
    );
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by Vetra. AI assisted drafting — human approval required before client use.",
          italics: true,
          size: 16,
          color: "888888",
        }),
      ],
      alignment: AlignmentType.LEFT,
      spacing: { before: 400 },
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  return Packer.toBlob(doc);
}

function claimParagraphs(claim: EvidenceClaim): Paragraph[] {
  const lines: Paragraph[] = [
    new Paragraph({
      children: [
        new TextRun({
          text: `${claim.supported ? "✓" : "⚠"} ${claim.claim}`,
          bold: true,
          size: 18,
        }),
      ],
      spacing: { before: 120, after: 40 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Section: ${claim.section}`,
          size: 16,
          color: "666666",
        }),
      ],
      spacing: { after: 40 },
    }),
  ];

  for (const src of claim.sources) {
    lines.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `[${src.kind}] ${src.label}: “${src.excerpt}”`,
            italics: true,
            size: 16,
          }),
        ],
        spacing: { after: 40 },
      })
    );
  }

  return lines;
}

export function dossierExportFilename(
  candidateName: string,
  ext: "docx" | "pdf"
) {
  const safe = candidateName.replace(/[^\w\-]+/g, "_").replace(/_+/g, "_");
  return `${safe}_dossier.${ext}`;
}
