import { jsPDF } from "jspdf";
import type { CandidateDossier } from "@/lib/types";

function wrapText(doc: jsPDF, text: string, maxWidth: number): string[] {
  return doc.splitTextToSize(text, maxWidth) as string[];
}

export function buildDossierPdf(input: {
  dossier: CandidateDossier;
  templateName?: string;
  mandateTitle?: string;
}): Blob {
  const { dossier, templateName, mandateTitle } = input;
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 48;
  const maxWidth = pageWidth - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const addWrapped = (
    text: string,
    opts: { fontSize?: number; style?: "normal" | "bold" | "italic"; color?: [number, number, number]; gap?: number } = {}
  ) => {
    const fontSize = opts.fontSize ?? 10;
    const style = opts.style ?? "normal";
    const color = opts.color ?? [30, 30, 30];
    doc.setFont("helvetica", style);
    doc.setFontSize(fontSize);
    doc.setTextColor(...color);
    const lines = wrapText(doc, text, maxWidth);
    const lineHeight = fontSize + 4;
    ensureSpace(lines.length * lineHeight + (opts.gap ?? 0));
    for (const line of lines) {
      doc.text(line, margin, y);
      y += lineHeight;
    }
    y += opts.gap ?? 6;
  };

  addWrapped(dossier.candidateName, { fontSize: 18, style: "bold", gap: 4 });
  addWrapped(`${dossier.targetRole} · ${dossier.client}`, {
    fontSize: 11,
    color: [90, 90, 90],
    gap: 2,
  });
  addWrapped(
    [
      templateName ? `Template: ${templateName}` : null,
      mandateTitle ? `Mandate: ${mandateTitle}` : null,
      `Status: ${dossier.status}`,
      dossier.approvedAt
        ? `Approved: ${new Date(dossier.approvedAt).toLocaleString()}`
        : "Not yet approved",
    ]
      .filter(Boolean)
      .join(" · "),
    { fontSize: 9, color: [120, 120, 120], gap: 16 }
  );

  for (const section of dossier.sections) {
    addWrapped(section.title, { fontSize: 13, style: "bold", gap: 6 });
    for (const block of section.content.split(/\n+/).filter(Boolean)) {
      addWrapped(block, { fontSize: 10, gap: 4 });
    }
    y += 8;
  }

  if (dossier.claims.length > 0) {
    addWrapped("Evidence appendix", { fontSize: 13, style: "bold", gap: 8 });
    for (const claim of dossier.claims) {
      addWrapped(`${claim.supported ? "[Supported]" : "[Unsupported]"} ${claim.claim}`, {
        fontSize: 9,
        style: "bold",
        gap: 2,
      });
      addWrapped(`Section: ${claim.section}`, {
        fontSize: 8,
        color: [100, 100, 100],
        gap: 2,
      });
      for (const src of claim.sources) {
        addWrapped(`[${src.kind}] ${src.label}: "${src.excerpt}"`, {
          fontSize: 8,
          style: "italic",
          color: [70, 70, 70],
          gap: 2,
        });
      }
      if (!claim.supported && claim.flaggedReason) {
        addWrapped(`Flag: ${claim.flaggedReason}`, {
          fontSize: 8,
          color: [140, 40, 40],
          gap: 6,
        });
      } else {
        y += 4;
      }
    }
  }

  addWrapped(
    "Generated by Vetra. AI assisted drafting — human approval required before client use.",
    { fontSize: 8, style: "italic", color: [130, 130, 130], gap: 0 }
  );

  return doc.output("blob");
}
